# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b642b5039a16154a5b1b7abd713267fb7c45bcf59db948a4a7e74bfa6ab704d387a3b76cec2a1dbdf7468d2845d9d21dca5a639d9978e5771d7cf60673782db

test:
  secret_key_base: 7b850481d8f775a51d3efa03722ec600aca48e4bcb26978cdaaaa778546a868cf0a9e4b3c845cf66d3239e2e849e71b285d823a627d87f41dd822cc434f34b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
